<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Car;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            // Mercedes cars
            ['user_id' => 3, 'brand_id' => 1, 'model' => 'S-Class', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 5000, 'fuel_type' => 'Gasoline', 'make' => 'Mercedes', 'transmission' => 'Automatic', 'drivetrian' => 'RWD', 'vin' => 'WDDXYZ987654', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 420, 'rating' => 4.8, 'num_of_ratings' => 2, 'price_per_day' => 25, 'status' => 'pending', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 1, 'model' => 'E-Class', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 25000, 'fuel_type' => 'Diesel', 'make' => 'Mercedes', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WDD654321234', 'brake' => 'ABS', 'year' => 2021, 'engine_hp' => 370, 'rating' => 4.6, 'num_of_ratings' => 1, 'price_per_day' => 18, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 1, 'model' => 'C-Class', 'availability' => 'Available', 'body' => 'Coupe', 'ac' => 'Yes', 'door' => 2, 'mileage' => 12000, 'fuel_type' => 'Gasoline', 'make' => 'Mercedes', 'transmission' => 'Automatic', 'drivetrian' => 'RWD', 'vin' => 'WDD987654321', 'brake' => 'ABS', 'year' => 2020, 'engine_hp' => 330, 'rating' => 4.7, 'num_of_ratings' => 2, 'price_per_day' => 20, 'status' => 'rejected', 'date_created' => now()],
            ['user_id' => 8, 'brand_id' => 1, 'model' => 'GLS', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 8000, 'fuel_type' => 'Gasoline', 'make' => 'Mercedes', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WDD123654789', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 450, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 28, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 12, 'brand_id' => 1, 'model' => 'G-Class', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 6000, 'fuel_type' => 'Gasoline', 'make' => 'Mercedes', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WDD654789123', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 500, 'rating' => 5.0, 'num_of_ratings' => 3, 'price_per_day' => 35, 'status' => 'accepted', 'date_created' => now()],

            // Audi cars
            ['user_id' => 12, 'brand_id' => 2, 'model' => 'A4', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 15000, 'fuel_type' => 'Diesel', 'make' => 'Audi', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WAU123456789', 'brake' => 'ABS', 'year' => 2021, 'engine_hp' => 250, 'rating' => 4.7, 'num_of_ratings' => 1, 'price_per_day' => 16, 'status' => 'pending', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 2, 'model' => 'Q7', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 5, 'mileage' => 25000, 'fuel_type' => 'Diesel', 'make' => 'Audi', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WAU987654321', 'brake' => 'ABS', 'year' => 2020, 'engine_hp' => 350, 'rating' => 4.8, 'num_of_ratings' => 2, 'price_per_day' => 20, 'status' => 'rejected', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 2, 'model' => 'A6', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 18000, 'fuel_type' => 'Gasoline', 'make' => 'Audi', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WAU456789123', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 300, 'rating' => 4.6, 'num_of_ratings' => 2, 'price_per_day' => 19, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 8, 'brand_id' => 2, 'model' => 'Q5', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 10000, 'fuel_type' => 'Hybrid', 'make' => 'Audi', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WAU789456123', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 320, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 22, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 2, 'model' => 'RS7', 'availability' => 'Available', 'body' => 'Coupe', 'ac' => 'Yes', 'door' => 2, 'mileage' => 5000, 'fuel_type' => 'Gasoline', 'make' => 'Audi', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'WAU321987654', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 560, 'rating' => 5.0, 'num_of_ratings' => 3, 'price_per_day' => 40, 'status' => 'accepted', 'date_created' => now()],

            // Honda cars
            ['user_id' => 8, 'brand_id' => 3, 'model' => 'Civic', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 10000, 'fuel_type' => 'Hybrid', 'make' => 'Honda', 'transmission' => 'CVT', 'drivetrian' => 'FWD', 'vin' => 'JHM123456789', 'brake' => 'ABS', 'year' => 2021, 'engine_hp' => 180, 'rating' => 4.5, 'num_of_ratings' => 1, 'price_per_day' => 30, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 12, 'brand_id' => 3, 'model' => 'Accord', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 12000, 'fuel_type' => 'Gasoline', 'make' => 'Honda', 'transmission' => 'CVT', 'drivetrian' => 'FWD', 'vin' => 'JHM987654321', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 200, 'rating' => 4.6, 'num_of_ratings' => 1, 'price_per_day' => 30, 'status' => 'pending', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 3, 'model' => 'CR-V', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 9000, 'fuel_type' => 'Hybrid', 'make' => 'Honda', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'JHM456789123', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 220, 'rating' => 4.7, 'num_of_ratings' => 2, 'price_per_day' => 32, 'status' => 'rejected', 'date_created' => now()],
            ['user_id' => 8, 'brand_id' => 3, 'model' => 'Pilot', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 15000, 'fuel_type' => 'Gasoline', 'make' => 'Honda', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'JHM321456987', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 280, 'rating' => 4.8, 'num_of_ratings' => 2, 'price_per_day' => 15, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 3, 'model' => 'Odyssey', 'availability' => 'Available', 'body' => 'Minivan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 8000, 'fuel_type' => 'Gasoline', 'make' => 'Honda', 'transmission' => 'Automatic', 'drivetrian' => 'FWD', 'vin' => 'JHM654789123', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 250, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 14, 'status' => 'accepted', 'date_created' => now()],

            // Toyota cars
            ['user_id' => 12, 'brand_id' => 4, 'model' => 'Camry', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 20000, 'fuel_type' => 'Gasoline', 'make' => 'Toyota', 'transmission' => 'Automatic', 'drivetrian' => 'FWD', 'vin' => 'JT123456789', 'brake' => 'ABS', 'year' => 2021, 'engine_hp' => 200, 'rating' => 4.4, 'num_of_ratings' => 1, 'price_per_day' => 80, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 4, 'model' => 'Corolla', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 18000, 'fuel_type' => 'Gasoline', 'make' => 'Toyota', 'transmission' => 'Automatic', 'drivetrian' => 'FWD', 'vin' => 'JT987654321', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 170, 'rating' => 4.6, 'num_of_ratings' => 1, 'price_per_day' => 85, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 4, 'model' => 'RAV4', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 12000, 'fuel_type' => 'Hybrid', 'make' => 'Toyota', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'JT456789123', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 220, 'rating' => 4.7, 'num_of_ratings' => 2, 'price_per_day' => 50, 'status' => 'pending', 'date_created' => now()],
            ['user_id' => 8, 'brand_id' => 4, 'model' => 'Highlander', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 14000, 'fuel_type' => 'Hybrid', 'make' => 'Toyota', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => 'JT321654987', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 240, 'rating' => 4.8, 'num_of_ratings' => 2, 'price_per_day' => 30, 'status' => 'rejected', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 4, 'model' => 'Tacoma', 'availability' => 'Available', 'body' => 'Truck', 'ac' => 'Yes', 'door' => 2, 'mileage' => 15000, 'fuel_type' => 'Gasoline', 'make' => 'Toyota', 'transmission' => 'Automatic', 'drivetrian' => '4WD', 'vin' => 'JT789456123', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 280, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 50, 'status' => 'accepted', 'date_created' => now()],

            // Tesla cars
            ['user_id' => 8, 'brand_id' => 5, 'model' => 'Model 3', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 10000, 'fuel_type' => 'Electric', 'make' => 'Tesla', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5YJ123456789', 'brake' => 'ABS', 'year' => 2021, 'engine_hp' => 450, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 20, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 12, 'brand_id' => 5, 'model' => 'Model S', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 8000, 'fuel_type' => 'Electric', 'make' => 'Tesla', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5YJ987654321', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 500, 'rating' => 5.0, 'num_of_ratings' => 2, 'price_per_day' => 25, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 5, 'model' => 'Model X', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 12000, 'fuel_type' => 'Electric', 'make' => 'Tesla', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5YJ654321987', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 480, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 28, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 12, 'brand_id' => 5, 'model' => 'Model Y', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 5000, 'fuel_type' => 'Electric', 'make' => 'Tesla', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5YJ123987654', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 470, 'rating' => 5.0, 'num_of_ratings' => 2, 'price_per_day' => 20, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 5, 'model' => 'Cybertruck', 'availability' => 'Available', 'body' => 'Truck', 'ac' => 'Yes', 'door' => 2, 'mileage' => 4000, 'fuel_type' => 'Electric', 'make' => 'Tesla', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5YJ789456123', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 600, 'rating' => 5.0, 'num_of_ratings' => 3, 'price_per_day' => 50, 'status' => 'rejected', 'date_created' => now()],

            // Acura cars
            ['user_id' => 12, 'brand_id' => 6, 'model' => 'MDX', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 12000, 'fuel_type' => 'Gasoline', 'make' => 'Acura', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5FR123456789', 'brake' => 'ABS', 'year' => 2021, 'engine_hp' => 290, 'rating' => 4.6, 'num_of_ratings' => 1, 'price_per_day' => 40, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 6, 'model' => 'RDX', 'availability' => 'Available', 'body' => 'SUV', 'ac' => 'Yes', 'door' => 4, 'mileage' => 10000, 'fuel_type' => 'Gasoline', 'make' => 'Acura', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5FR987654321', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 280, 'rating' => 4.7, 'num_of_ratings' => 1, 'price_per_day' => 50, 'status' => 'rejected', 'date_created' => now()],
            ['user_id' => 3, 'brand_id' => 6, 'model' => 'TLX', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 8000, 'fuel_type' => 'Gasoline', 'make' => 'Acura', 'transmission' => 'Automatic', 'drivetrian' => 'FWD', 'vin' => '5FR654321789', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 272, 'rating' => 4.8, 'num_of_ratings' => 2, 'price_per_day' => 30, 'status' => 'accepted', 'date_created' => now()],
            ['user_id' => 8, 'brand_id' => 6, 'model' => 'ILX', 'availability' => 'Available', 'body' => 'Sedan', 'ac' => 'Yes', 'door' => 4, 'mileage' => 6000, 'fuel_type' => 'Gasoline', 'make' => 'Acura', 'transmission' => 'Automatic', 'drivetrian' => 'FWD', 'vin' => '5FR321654987', 'brake' => 'ABS', 'year' => 2023, 'engine_hp' => 201, 'rating' => 4.9, 'num_of_ratings' => 2, 'price_per_day' => 40, 'status' => 'pending', 'date_created' => now()],
            ['user_id' => 5, 'brand_id' => 6, 'model' => 'NSX', 'availability' => 'Available', 'body' => 'Coupe', 'ac' => 'Yes', 'door' => 2, 'mileage' => 5000, 'fuel_type' => 'Hybrid', 'make' => 'Acura', 'transmission' => 'Automatic', 'drivetrian' => 'AWD', 'vin' => '5FR789456123', 'brake' => 'ABS', 'year' => 2022, 'engine_hp' => 573, 'rating' => 5.0, 'num_of_ratings' => 2, 'price_per_day' => 40, 'status' => 'accepted', 'date_created' => now()],
        ];

        foreach ($cars as $car) {
            Car::create($car);
        }
    }
}
